twig:
    default_path: '%kernel.project_dir%/templates'
    globals:
        RollDice: '@App\Service\RollDice'
        Inventory: '@App\Service\Inventory'

when@test:
    twig:
        strict_variables: true
        